#pragma once

class CAffect
{
	public:
		uint32_t	dwType;
		uint8_t    bApplyOn;
		int32_t    lApplyValue;
		uint32_t   dwFlag;
		int32_t	lDuration;
		int32_t	lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,

	AFFECT_BLOCK_CHAT,
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,
	AFFECT_DEF_GRADE,
#ifdef ENABLE_WOLFMAN_CHARACTER // @correction190
	AFFECT_BLEEDING,
#endif
#ifdef __ELEMENT_ADD__
	AFFECT_MOUNT_FALL,							// 230
	AFFECT_NO_RECOVERY,							// 231
	AFFECT_REDUCE_CAST_SPEED,					// 232
#endif
#ifdef __12ZI__
	AFFECT_ATT_GRADE_DOWN,						// 233
	AFFECT_DEF_GRADE_DOWN,						// 234
	AFFECT_CRITICAL_PCT_DOWN,					// 235
	AFFECT_CZ_UNLIMIT_ENTER,					// 236
#endif

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING = 301,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,
	AFFECT_ITEM_BONUS		= 501,
	AFFECT_SAFEBOX		= 502,
	AFFECT_AUTOLOOT		= 503,
	AFFECT_FISH_MIND		= 504,
	AFFECT_MARRIAGE_FAST	= 505,
	AFFECT_GOLD_BONUS		= 506,
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,
	AFFECT_NO_DEATH_PENALTY	= 511,
	AFFECT_SKILL_BOOK_BONUS	= 512,
	AFFECT_SKILL_NO_BOOK_DELAY	= 513,

	AFFECT_HAIR	= 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1 = 519,
	AFFECT_CUBE_2 = 520,
	AFFECT_CUBE_3 = 521,
	AFFECT_CUBE_4 = 522,
	AFFECT_CUBE_5 = 523,
	AFFECT_CUBE_6 = 524,
	AFFECT_CUBE_7 = 525,
	AFFECT_CUBE_8 = 526,
	AFFECT_CUBE_9 = 527,
	AFFECT_CUBE_10 = 528,
	AFFECT_CUBE_11 = 529,
	AFFECT_CUBE_12 = 530,

	AFFECT_BLEND = 531,

	AFFECT_HORSE_NAME = 532,
	AFFECT_MOUNT_BONUS = 533,

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,

#ifdef __ALIGN_RENEWAL__
	AFFECT_ALIGN_BONUS1,
	AFFECT_ALIGN_BONUS2,
	AFFECT_ALIGN_BONUS3,
#endif

#ifdef __GUILD_DRAGONLAIR__
	AFFECT_STATUE,
#endif

#ifdef __GROWTH_PET__
	AFFECT_NEW_PET,
#endif

#if defined(__MINI_GAME_ATTENDANCE__) || defined(__MINI_GAME_MONSTERBACK__)
	AFFECT_EXP_BONUS_EVENT,
	AFFECT_ATT_SPEED_SLOW,
#endif
#ifdef __SOUL__
	AFFECT_SOUL,
#endif

	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,
	AFF_DUNGEON_UNIQUE,

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_JEONGWIHON,
	AFF_GEOMGYEONG,
	AFF_CHEONGEUN,
	AFF_GYEONGGONG,
	AFF_EUNHYUNG,
	AFF_GWIGUM,
	AFF_TERROR,
	AFF_JUMAGAP,
	AFF_HOSIN,
	AFF_BOHO,
	AFF_KWAESOK,
	AFF_MANASHIELD,
	AFF_MUYEONG,
	AFF_REVIVE_INVISIBLE,
	AFF_FIRE,
	AFF_GICHEON,
	AFF_JEUNGRYEOK,
	AFF_TANHWAN_DASH,
	AFF_PABEOP,
	AFF_CHEONGEUN_WITH_FALL,
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,

	AFF_CHINA_FIREWORK,
	AFF_HAIR,
	AFF_GERMANY,
	AFF_RAMADAN_RING,

#ifdef ENABLE_WOLFMAN_CHARACTER // @correction190
	AFF_BLEEDING,
	AFF_RED_POSSESSION,
	AFF_BLUE_POSSESSION,
#endif

#ifdef __GUILD_DRAGONLAIR__
	AFF_STATUE1,
	AFF_STATUE2,
	AFF_STATUE3,
	AFF_STATUE4,
#endif

#ifdef __12ZI__
	AFF_ELECTRIC_SHOCK,					// 46
	AFF_CONFUSION,						// 47
#endif
#ifdef __SOUL__
	AFF_SOUL_RED,
	AFF_SOUL_BLUE,
	AFF_SOUL_MIX,
#endif

	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

enum AffectVariable
{

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};


